-- Attribution d'acquisition (first-touch) sur le Lead.
ALTER TABLE "Lead" ADD COLUMN "utmSource"   TEXT;
ALTER TABLE "Lead" ADD COLUMN "utmMedium"   TEXT;
ALTER TABLE "Lead" ADD COLUMN "utmCampaign" TEXT;
ALTER TABLE "Lead" ADD COLUMN "utmTerm"     TEXT;
ALTER TABLE "Lead" ADD COLUMN "utmContent"  TEXT;
ALTER TABLE "Lead" ADD COLUMN "gclid"       TEXT;
ALTER TABLE "Lead" ADD COLUMN "landingPage" TEXT;
ALTER TABLE "Lead" ADD COLUMN "referrer"    TEXT;
ALTER TABLE "Lead" ADD COLUMN "channel"     TEXT;
